//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestLocalization.Resources.Home.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects..
        /// </summary>
        public static string TextGetMoreLibrariesCaption {
            get {
                return ResourceManager.GetString("TextGetMoreLibrariesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get more libraries.
        /// </summary>
        public static string TextGetMoreLibrariesHeading {
            get {
                return ResourceManager.GetString("TextGetMoreLibrariesHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that enables a clean separation of concerns and gives you full control over markup for enjoyable, agile development..
        /// </summary>
        public static string TextGettingStartedCaption {
            get {
                return ResourceManager.GetString("TextGettingStartedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Started.
        /// </summary>
        public static string TextGettingStartedHeading {
            get {
                return ResourceManager.GetString("TextGettingStartedHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript..
        /// </summary>
        public static string TextJumbo {
            get {
                return ResourceManager.GetString("TextJumbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more &amp;raquo;.
        /// </summary>
        public static string TextLearnMore {
            get {
                return ResourceManager.GetString("TextLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can easily find a web hosting company that offers the right mix of features and price for your applications..
        /// </summary>
        public static string TextWebHostingCaption {
            get {
                return ResourceManager.GetString("TextWebHostingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Hosting.
        /// </summary>
        public static string TextWebHostingHeading {
            get {
                return ResourceManager.GetString("TextWebHostingHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string TitleHomePage {
            get {
                return ResourceManager.GetString("TitleHomePage", resourceCulture);
            }
        }
    }
}
